data("mtcars")
install("dplyr")
install("tidyr")
library(dplyr)
library(tidyr)
head(mtcars)
mtcars$car<- rownames(mtcars)
mtcars <- mtcars[, c(12, 1:11)]
mtcarsNew <- mtcars %>% gather(attribute, value, -car)
head(mtcarsNew)
mtcarsSpread <- mtcarsNew %>% spread(attribute, value)
head(mtcarsSpread)
mtcars_unite <- mtcars %>% unite(details,mpg,cyl,disp,hp,sep = ',')
head(mtcars_unite)
mtcars_sep <- mtcars_unite %>% separate(details, c('mpg','cyl','disp','hp'), sep =',')
head(mtcars_sep)