install.packages("dplyr","tidyverse") 
library(dplyr)
library(tidyverse) 
head(diamonds)
str(diamonds) 
glimpse(diamonds) 
colnames(diamonds)
rename(diamonds, carat_new = carat, cut_new = cut) 
summarize(diamonds, mean_carat = mean(carat)) 
mutate(diamonds, discount_price = (price-(0.1*price))) 
filter(diamonds,cut=='Premium',color=='E') 
arrange(diamonds,table,price)